// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int runs =Integer.parseInt(args[0]);
		int count1 = 0;
		int count2 = 0;
		for(int i = 0; i < runs; i++) {
			double num = Math.random();
			if (num > 0.5) count1++;
			else count2++;
		} 
		if (count1 > count2 && count2 != 0) {
			System.out.println("> 0.5: " + count1 + " times");
			System.out.println("<= 0.5: " + count2 + " times");
			System.out.println("Ratio: " + count2 / (double)count1);
		}
		else if (count2 > count1 && count1 != 0) {
			System.out.println("> 0.5: " + count1 + " times");
			System.out.println("<= 0.5: " + count2 + " times");
			System.out.println("Ratio: " + count1 / (double)count2);
		}
		else {
			System.out.println("> 0.5: " + count1 + " times");
			System.out.println("<= 0.5: " + count2 + " times");
		}
	}
}
